/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.danman85.gang.of.four;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
